### ISSUE TITLE
Money Variables

### ISSUE THREAD

**Issue by juliebisharyan** [ucbsoj/choose-your-own-adventure#2]
Hi Jrue,

This issue is related to what we were talking about earlier today. Basically, I was wondering if there was a way to either change the way the money variables change after choices are made to reflect the yearly expenses/revenue or if there was a way to carry on certain expenses into the other yearly questions.

For instance, in year 1, if the player chooses to rent an apartment, that would be an expense that is subtracted from their total every year, not just for that first question.

Basically, my hope is for the total money variable after each year/question to reflect a combination of the salary + basic living expenses + leftover money from the previous year/question + whatever the choice the player makes on the given question (if it's money related). 

I made this [spreadsheet ](https://docs.google.com/spreadsheets/d/1OYfjg8Ju4LP_d0GkackV_Nlm_WBpwkSBGSf2RY3APbE/edit#gid=660944279) that shows what each of the ending balance would be given the choices the players make. There are different versions in the different sheets depending on the housing choices they make (since those are the big expense changes). I made it so that the expenses change each year to account for inflation and for the salary to also go up the teacher's salary schedule. 

The money variable differs from the motivation/energy levels because those variable changes don't carry onto the years/questions. 

I hope this makes sense. Again, I understand if it's way too complicated. I was considering just scraping the money variable altogether and just writing the end of the year expense in a p tag. Or finding another way to represent the expenses. If you have any suggestions on ways to make this simpler, please let me know! Thank you again.

Best,
Julie

**Comment by jrue** [comment]
add two new attributes

```html
data-year="1"
data-continuing-expense="-2000"
```

then later on, in year 5, suddenly we have another expense.

```html
data-year="4"
data-continuing-expense="-1000"
```
In the example above, if the user chose both options, starting year 4, they will be losing 3000. 

```html
data-year="5"
data-continuing-expense="1000"
```

in the example above, if the user had picked all of these options, at this point in year 5, the deduction is 2000.
